spring.application.name=mldsa
spring.datasource.url=jdbc:postgresql://localhost:5432/mldsa
spring.datasource.name=mldsa
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
