-- Baseline schema, adopted with the two-tier banking restructure on a fresh database
-- (TWO_TIER_BANKING_PLAN.md §11).
--
-- Generated from the JPA entities as they stood at that point, then given readable
-- constraint names. From here on the schema belongs to these migrations: Hibernate only
-- validates it (ddl-auto=validate), so any entity change needs a new V<n>__*.sql beside
-- this one. That includes adding an enum value — the CHECK constraints below list every
-- permitted value, and nothing will revise them automatically.

-- One schema per owning module, inside one physical database.
create schema identity;
create schema ledger;
create schema payments;
create schema cards;
create schema filetransfer;

-- ---------------------------------------------------------------------------------------
-- Identity & Access
-- ---------------------------------------------------------------------------------------

create table identity.users (
    user_id          bigint generated by default as identity,
    user_name        varchar(255) not null,
    password         varchar(255),
    public_key       varchar(255),
    private_key      varchar(255),
    role             varchar(255) not null,
    bic              varchar(11),
    -- Set on INSTITUTION accounts only.
    institution_code varchar(8),
    constraint users_pkey primary key (user_id),
    constraint users_user_name_key unique (user_name),
    constraint users_institution_code_key unique (institution_code),
    constraint users_role_check check (role in ('NORMAL_USER', 'INSTITUTION', 'BANK'))
);

-- ---------------------------------------------------------------------------------------
-- Ledger
-- ---------------------------------------------------------------------------------------

create table ledger.accounts (
    account_id     bigint generated by default as identity,
    account_number varchar(16) not null,
    owner_id       bigint not null,
    account_type   varchar(255) not null,
    -- The institution responsible for the account: a customer's bank, or for a settlement
    -- account the institution itself.
    institution_id bigint not null,
    currency       varchar(3) not null,
    opened_at      timestamp(6) with time zone not null,
    constraint accounts_pkey primary key (account_id),
    constraint accounts_account_number_key unique (account_number),
    constraint accounts_account_type_check check (account_type in ('CUSTOMER', 'SETTLEMENT')),
    constraint accounts_owner_fk foreign key (owner_id) references identity.users,
    constraint accounts_institution_fk foreign key (institution_id) references identity.users
);

-- Deliberately no balance column anywhere: a balance is the sum of an account's postings.
create table ledger.postings (
    posting_id      bigint generated by default as identity,
    account_id      bigint not null,
    direction       varchar(255) not null,
    amount          numeric(19, 2) not null,
    description     varchar(255),
    transaction_ref varchar(36) not null,
    posted_at       timestamp(6) with time zone not null,
    constraint postings_pkey primary key (posting_id),
    constraint postings_direction_check check (direction in ('CREDIT', 'DEBIT')),
    constraint postings_account_fk foreign key (account_id) references ledger.accounts
);

-- ---------------------------------------------------------------------------------------
-- Payments
-- ---------------------------------------------------------------------------------------

create table payments.deposits (
    deposit_id      bigint generated by default as identity,
    account_id      bigint not null,
    amount          numeric(19, 2) not null,
    description     varchar(255),
    transaction_ref varchar(36) not null,
    signature       varchar(255) not null,
    deposited_at    timestamp(6) with time zone not null,
    constraint deposits_pkey primary key (deposit_id),
    constraint deposits_account_fk foreign key (account_id) references ledger.accounts
);

create table payments.payments (
    payment_id      bigint generated by default as identity,
    from_account_id bigint not null,
    -- Null when a payment was refused because no payable recipient existed.
    to_account_id   bigint,
    amount          numeric(19, 2) not null,
    description     varchar(255),
    status          varchar(255) not null,
    failure_reason  varchar(255),
    transaction_ref varchar(36),
    signature       varchar(255),
    created_at      timestamp(6) with time zone not null,
    constraint payments_pkey primary key (payment_id),
    constraint payments_status_check check (status in ('COMPLETED', 'FAILED')),
    constraint payments_from_account_fk foreign key (from_account_id) references ledger.accounts,
    constraint payments_to_account_fk foreign key (to_account_id) references ledger.accounts
);

create table payments.payment_links (
    id                   bigint generated by default as identity,
    link_id              varchar(36) not null,
    requester_account_id bigint not null,
    amount               numeric(19, 2) not null,
    description          varchar(255),
    status               varchar(255) not null,
    payment_id           bigint,
    expires_at           timestamp(6) with time zone not null,
    paid_at              timestamp(6) with time zone,
    created_at           timestamp(6) with time zone not null,
    constraint payment_links_pkey primary key (id),
    constraint payment_links_link_id_key unique (link_id),
    constraint payment_links_status_check check (status in ('PENDING', 'PAID', 'CANCELLED', 'EXPIRED')),
    constraint payment_links_requester_account_fk foreign key (requester_account_id) references ledger.accounts,
    constraint payment_links_payment_fk foreign key (payment_id) references payments.payments
);

-- ---------------------------------------------------------------------------------------
-- Card Services
-- ---------------------------------------------------------------------------------------

create table cards.debit_cards (
    card_id             bigint generated by default as identity,
    card_number         varchar(16) not null,
    account_id          bigint not null,
    expires_on          date not null,
    status              varchar(255) not null,
    pin_hash            varchar(255) not null,
    failed_pin_attempts integer not null,
    issued_at           timestamp(6) with time zone not null,
    constraint debit_cards_pkey primary key (card_id),
    constraint debit_cards_card_number_key unique (card_number),
    constraint debit_cards_status_check check (status in ('ACTIVE', 'BLOCKED', 'EXPIRED')),
    constraint debit_cards_account_fk foreign key (account_id) references ledger.accounts
);

-- ---------------------------------------------------------------------------------------
-- File Transfer & Review
-- ---------------------------------------------------------------------------------------

create table filetransfer.file_transfers (
    transfer_id         bigint generated by default as identity,
    sender_id           bigint not null,
    receiver_id         bigint not null,
    original_filename   varchar(255) not null,
    stored_filename     varchar(255) not null,
    stored_xml_filename varchar(255),
    file_hash           varchar(255),
    xml_hash            varchar(255),
    signature           varchar(255),
    signature_valid     boolean,
    uetr                varchar(36),
    status              varchar(255) not null,
    sent_at             timestamp(6) with time zone not null,
    downloaded_at       timestamp(6) with time zone,
    reviewed_at         timestamp(6) with time zone,
    rejection_reason    text,
    constraint file_transfers_pkey primary key (transfer_id),
    constraint file_transfers_stored_filename_key unique (stored_filename),
    constraint file_transfers_stored_xml_filename_key unique (stored_xml_filename),
    constraint file_transfers_status_check check (status in ('SENT', 'APPROVED', 'REJECTED', 'DOWNLOADED')),
    constraint file_transfers_sender_fk foreign key (sender_id) references identity.users,
    constraint file_transfers_receiver_fk foreign key (receiver_id) references identity.users
);

-- ---------------------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------------------

-- Postgres does not index a foreign key by itself, and Hibernate generates none. These cover
-- the lookups made constantly: every balance sums an account's postings, every customer
-- request resolves the caller's own account, and every institution-scoped query filters by
-- institution and account type.
create index postings_account_idx on ledger.postings (account_id);
create index accounts_owner_idx on ledger.accounts (owner_id);
create index accounts_institution_type_idx on ledger.accounts (institution_id, account_type);
