-- ISO 20022 pacs.008 for the interbank leg: the message the paying institution sends the
-- receiving one for every inter-bank payment.
--
-- The XML itself is not stored here — it goes to encrypted file storage like every other
-- document, under stored_filename. What this table holds is the record of the message and the
-- exact values its signature was built from, so the signed envelope can be rebuilt later
-- rather than recomputed from data that may have changed since.
--
-- One message per payment (a payment inside one bank produces none), enforced by the unique
-- key on payment_id.
create table payments.settlement_messages (
    message_id          bigint generated by default as identity,
    payment_id          bigint not null,
    debtor_agent_id     bigint not null,
    creditor_agent_id   bigint not null,
    -- The agents' codes as they stood when the message was signed.
    debtor_agent_code   varchar(8) not null,
    creditor_agent_code varchar(8) not null,
    -- Also the ledger's transaction_ref for the payment's four postings.
    uetr                varchar(36) not null,
    message_type        varchar(20) not null,
    amount              numeric(19, 2) not null,
    currency            varchar(3) not null,
    stored_filename     varchar(255) not null,
    xml_hash            varchar(255) not null,
    signature           varchar(255) not null,
    created_at          timestamp(6) with time zone not null,
    constraint settlement_messages_pkey primary key (message_id),
    constraint settlement_messages_payment_key unique (payment_id),
    constraint settlement_messages_uetr_key unique (uetr),
    constraint settlement_messages_stored_filename_key unique (stored_filename),
    constraint settlement_messages_payment_fk foreign key (payment_id) references payments.payments,
    constraint settlement_messages_debtor_agent_fk foreign key (debtor_agent_id) references identity.users,
    constraint settlement_messages_creditor_agent_fk foreign key (creditor_agent_id) references identity.users
);

-- Both sides are queried: an institution reads the messages it sent and the ones it received.
create index settlement_messages_debtor_agent_idx on payments.settlement_messages (debtor_agent_id);
create index settlement_messages_creditor_agent_idx on payments.settlement_messages (creditor_agent_id);
