-- Retried requests stop paying twice.
--
-- A client whose request times out has no way to know whether the payment happened, so it
-- retries — and today that produces a second payment, a second set of postings and, across
-- banks, a second pacs.008. Mobile clients on poor connections do this constantly. The worst
-- case is a deposit: a teller double-clicking at the counter manufactures money that was
-- never handed over.
--
-- The caller sends an Idempotency-Key header; the first request through claims it, and any
-- later request carrying the same key is answered with the stored response instead of being
-- executed again.

create table payments.idempotency_keys (
    idempotency_id  bigint generated by default as identity,
    -- Whose key this is. Two callers may pick the same key without colliding, and one
    -- caller cannot replay another's response by guessing a key.
    caller_id       bigint not null,
    idempotency_key varchar(120) not null,
    -- The request this key was first used for: method, path and a hash of the body. A key
    -- reused with different content is a client bug, and answering it with the first
    -- request's response would hide that by confirming a payment that was never made.
    request_method  varchar(8) not null,
    request_path    varchar(255) not null,
    request_hash    varchar(64) not null,
    -- Null until the request finishes. A row in this state is one still in flight, which is
    -- what a concurrent duplicate — rather than a later retry — finds.
    response_status integer,
    response_body   text,
    created_at      timestamp(6) with time zone not null,
    completed_at    timestamp(6) with time zone,
    constraint idempotency_keys_pkey primary key (idempotency_id),
    constraint idempotency_keys_caller_fk foreign key (caller_id) references identity.users
);

-- This constraint is the whole mechanism. Claiming a key is an insert that either succeeds or
-- violates this, and the database decides which — so two identical requests arriving at the
-- same instant cannot both find the key unclaimed and both proceed. A check that read first
-- and then inserted would have exactly the race this table exists to remove, which is the
-- same lesson the payer's account lock taught one layer down.
create unique index idempotency_keys_caller_key on payments.idempotency_keys (caller_id, idempotency_key);

-- Retention is a later concern: these rows are small and only accumulate for requests that
-- carried a key. Sweeping them wants deciding deliberately, since deleting a key makes the
-- request it guarded repeatable again.
create index idempotency_keys_created_idx on payments.idempotency_keys (created_at);
